name: api test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  #workflow_dispatch:
  #schedule:
    #- cron: "30 6 * * *"

jobs:
  smoke-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      #       - name: Setup selenium Grid
      #         run: docker-compose up -d

      - name: Build with Maven
        run: mvn clean test site -DsuiteFile=api_regression.xml --settings settings.xml
        env:
          TECH_USER: ${{ secrets.TECH_USER }}
          TECH_USER_TOKEN: ${{ secrets.TECH_USER_TOKEN}}

      #       - name: Cleanup selenium Grid
      #         run: docker-compose down

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from smt
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

